Repository Git-kkalnane/starbucks-frontend, pull requests merged in 2025-06, with the labels that each got.

#9 Feat: SVG 파일로 icon 대체
  package.json
  src/assets/icons/account.svg
  src/assets/icons/back-edit.svg
  src/assets/icons/back.svg
  src/assets/icons/cart.svg
  src/assets/icons/customer-service.svg
  src/assets/icons/delivery.svg
  src/assets/icons/dt-icon.svg
  src/assets/icons/history.svg
  src/assets/icons/home.svg
  src/assets/icons/location.svg
  src/assets/icons/lock.svg
  src/assets/icons/now-brewing-icon.svg
  src/assets/icons/order.svg
  src/assets/icons/other.svg
  src/assets/icons/pay.svg
  src/assets/icons/receipt.svg
  src/assets/icons/search-alt-1-svgrepo-com.svg
  src/assets/icons/search.svg
  src/assets/icons/shopping-bag.svg
  src/assets/icons/sort-desc-icon.svg
  src/components/common/customHeader.jsx
  src/navigation/Navigation.jsx
  vite.config.js
Labels: UI

#10 feat: Other.jsx UI 추가
  src/App.jsx
  src/components/other/auth_panel/AuthPanel.jsx
  src/components/other/service_panel/ServiceItem.jsx
  src/components/other/service_panel/ServicePanel.jsx
  src/components/other/store_location/StoreLocation.jsx
  src/layouts/CommonLayout.jsx
  src/pages/MockPage.jsx
  src/pages/Other.jsx
Labels: UI, feature

#43 Update daily_work_report.yml
  .github/DISCUSSION_TEMPLATE/daily_work_report.yml
Labels: documentation, .github file

#49 Fix: 장바구니 totalPrice가 고정되었던 문제 해결
  src/pages/Cart.jsx
Labels: fix

#41 Feat: 매장 리스트 페이지 생성
  .gitignore
  package.json
  src/App.jsx
  src/components/common/LoadingSpinner.jsx
  src/components/common/customHeader.jsx
  src/components/shop/FilterTab.jsx
  src/components/shop/ShopListPanel.jsx
  src/layouts/Layout.css
  src/pages/shop/ShopList.jsx
  src/services/shopService.js
  tailwind.config.js
  vite.config.js
Labels: API, UI, feature

#46 Feat: 매장 디테일 페이지 생성
  src/App.jsx
  src/components/shop/shop_detail/FacilityIcons.jsx
  src/components/shop/shop_detail/OrderTypeSelector.jsx
  src/components/shop/shop_detail/ShopBasicInfo.jsx
  src/components/shop/shop_detail/ShopHoursAndDirections.jsx
  src/components/shop/shop_detail/ShopImage.jsx
  src/pages/shop/ShopDetail.jsx
Labels: UI, feature

#59 Update daily_work_report.yml
  .github/DISCUSSION_TEMPLATE/daily_work_report.yml
Labels: documentation

#57 Feat: order UI 입히기
  src/components/order/MenuList.jsx
  src/components/order/MenuTab.jsx
  src/components/order/OrderNavigationBar.jsx
  src/components/order/styles/OrderNavigationBar.css
  src/pages/Order.jsx
  src/services/OrderService.js
Labels: UI, feature

#62 Refactor/pay page UI
  src/components/charge/ChargeModal.jsx
  src/pages/Pay.jsx
Labels: refactor, UI, UI fix

#63 Feature: MenuDetail 페이지 추가
  package.json
  src/App.jsx
  src/assets/icons/back.svg
  src/components/common/customBtn.jsx
  src/components/common/customHeader.jsx
  src/components/menu/MenuAction.jsx
  src/components/menu/MenuHeader.jsx
  src/components/menu/MenuInfo.jsx
  src/components/menu/TemperatureToggle.jsx
  src/pages/menu/MenuDetail.jsx
  tailwind.config.js
Labels: UI, feature

#66 feature: Pay 페이지와 하위 페이지 및 컴포넌트 구현
  package-lock.json
  package.json
  public/images/card.png
  src/App.jsx
  src/components/charge/ChargeModal.jsx
  src/components/charge/UnitItem.jsx
  src/components/charge/UnitSelector.jsx
  src/components/common/customBtn.jsx
  src/components/common/customHeader.jsx
  src/components/common/customText.jsx
  src/components/pay/Card.jsx
  src/pages/Charge.jsx
  src/pages/Pay.jsx
Labels: UI, feature

#79 feature: 개인정보 페이지 및 하위 페이지 구현
  src/App.css
  src/App.jsx
  src/assets/icons/forward-icon.svg
  src/components/common/customBtn.jsx
  src/pages/account/Account.jsx
  src/pages/account/NickNameEdit.jsx
  src/pages/account/PasswordEdit.jsx
Labels: UI, feature

#80 refactor: MenuConfigurator에서 사용되는 클래스와 변수 이름 변경
  src/components/common/QuantityControl.jsx
  src/components/menu/ConfiguratorFooter.jsx
  src/hooks/order/index.js
  src/hooks/order/useSyrupCount.js
  src/pages/menu/MenuConfigurator.jsx
Labels: refactor

#81 Feat: 임시로 데이터를 받아올 노션 API 개발
  src/components/order/MenuList.jsx
  src/pages/Order.jsx
  src/services/OrderService.js
  src/services/shopService.js
  vite.config.js
Labels: feature

#87 feat: UserContext.jsx와 추가 AuthService.js 추가
  src/contexts/UserContext.jsx
  src/main.jsx
  src/reducers/userReducer.js
  src/services/AuthService.js
Labels: feature, context

#99 fix: 누락된 TemperatureDisplay UI 추가
  src/components/menu/TemperatureDisplay.jsx
Labels: fix, UI, feature

#101 Feat: 음료와 디저트 로직 분리 (#100)
  src/components/menu/MenuAction.jsx
  src/components/menu/OptionsItem.jsx
  src/components/menu/menu_detail/MenuDetailFooter.jsx
  src/components/menu/menu_detail/MenuDetailPanel.jsx
  src/components/menu/menu_detail/TemperatureDisplay.jsx
  src/components/menu/menu_detail/TemperaturePanel.jsx
  src/components/menu/menu_detail/TemperatureToggle.jsx
  src/hooks/order/index.js
  src/hooks/order/useOptionCount.js
  src/hooks/order/useSyrupCount.js
  src/hooks/useMenuConfigurator.js
  src/pages/menu/MenuConfigurator.jsx
  src/pages/menu/MenuDetail.jsx
  src/services/OrderService.js
Labels: refactor, UI fix

#103 feat: Signup 페이지 nickname input UI 추가 (#102)
  src/components/common/TextInput.jsx
  src/components/signup/FormFields.jsx
  src/components/signup/SignupForm.jsx
  src/components/signup/TermsAgreement.jsx
  src/components/signup/validator.js
  src/pages/Signup.jsx
Labels: UI, feature

#109 Fix: cart 아이템 수량 조절 기능 수정
  src/hooks/useMenuConfigurator.js
  src/pages/Cart.jsx
  src/pages/menu/MenuConfigurator.jsx
  src/pages/menu/MenuDetail.jsx
Labels: fix, UI fix

#111 Feat: Cart에 담긴 데이터 삭제 로직 (#110)
  src/pages/Cart.jsx
  src/pages/menu/MenuConfigurator.jsx
Labels: feature

#116 Feat/#115 login api
  src/components/auth/signup/SignupForm.jsx
  src/services/AuthService.js
  vite.config.js
Labels: API, feature

#119 Feat/#118 store api connect
  src/pages/shop/ShopDetail.jsx
  src/services/shopService.js
Labels: API, feature

#123 fix: 디저트 안 보임 에러 수정
  src/_utils/validators.js
  src/components/cart/CartItem.jsx
  src/components/order/MenuList.jsx
  src/components/order/MenuTab.jsx
  src/hooks/useCart.js
  src/hooks/useMenuConfigurator.js
  src/pages/menu/MenuConfigurator.jsx
  src/pages/menu/MenuDetail.jsx
  src/pages/order/Order.jsx
Labels: fix, UI fix
